# Benchmarking Logistic, Tree, Forest, and XGBoost Pipelines for Breast‑Cancer Detection

In this project we will analyze breast cancer data and create machine learning models to predict breast cancer.

In [4]:
# Making necessary imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [39]:
# Downloading the data from kaggle using kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/breast-cancer-dataset")

print("Path to dataset files:", path)

100%|██████████████████████████████████████████████████████████████████████████████| 48.6k/48.6k [00:00<00:00, 293kB/s]


Extracting files...
Path to dataset files: C:\Users\Hp\.cache\kagglehub\datasets\yasserh\breast-cancer-dataset\versions\1


In [47]:
# Loading the data into a pandas DataFrame
data = pd.read_csv(r"C:/Users/Hp/.cache/kagglehub/datasets/yasserh/breast-cancer-dataset/versions/1/breast-cancer.csv")

In [51]:
# Printing the first five rows of the data
data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [53]:
# Calling .info() on the data to get a better understanding of the columns
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

From the `.info()` method called on data it can be seen that there are no missing values. Also the columns are in consistent data types and so there is no need for data cleaning. We can now move on to Machine Learning

## Machine Learning

### Logistic Regression

Since the target column of the breast cancer data is categorical this machine learning problem is a classification problem. To start 
our model development we will use a logistic regression model which is good for basic classification tasks. Depending on the performance of the model we will decide to develop more powerful models to obtain better results

In [71]:
# We will begin by importing the Logistic Regression model from the scikit-learn library
from sklearn.linear_model import LogisticRegression

In [73]:
# Importing train test split from scikit-learn library
from sklearn.model_selection import train_test_split

In [91]:
# Separating the data into features and target
X = data.iloc[:,2:]#feautures
y = data.iloc[:,1]#target

In [93]:
# Splitting features and target into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

Since the values in the columns are of different scales of avrying magnitude, this can affect the quality of the model. To overcome this we will scale the columns to the same scale in order to enhance training of the model and accuracy of
the predictions. We will make use of the StandardScaler from the scikit-learn library

In [101]:
# Importing StandarScaler
from sklearn.preprocessing import StandardScaler

In [105]:
# Instanting StandardScaler as scaler
scaler = StandardScaler()

In [107]:
# Instantiating a Logistic Regression model as logmodel
logmodel = LogisticRegression()

Instead of separately scaling the data and then training the model and predicting we can simplify this by
using a pipeline. We'll make use of the `make_pipeline` function from scikit-learn

In [167]:
# Importing make_pipeline
from sklearn.pipeline import make_pipeline

In [169]:
# Making a pipeline consisting of StandardScaler and the Logistic Regression model
pipeline_log = make_pipeline(scaler, logmodel)

In [171]:
# Fitting the pipeline object to the training data 
pipeline_log.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

Now that we have trained the Logistic Regression model we can now predict on 
the test data and evaluate our model's performance

In [173]:
# Making predictions on the test data
y_pred = pipeline.predict(X_test)
# Predicting probabilities to be used in roc_auc_score
y_pred_probs = pipeline.predict_proba(X_test)[:, 1]

In [175]:
# Importing necessary tools to evaluate the model
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score

In [177]:
# Printing the confusion matrix
print('For the Logistic Regression Model:\n')
print(confusion_matrix(y_test, y_pred))
print('\n')
# Printing the classification report
print(classification_report(y_test, y_pred))

For the Logistic Regression Model:

[[104   1]
 [  3  63]]


              precision    recall  f1-score   support

           B       0.97      0.99      0.98       105
           M       0.98      0.95      0.97        66

    accuracy                           0.98       171
   macro avg       0.98      0.97      0.98       171
weighted avg       0.98      0.98      0.98       171



In [179]:
# Printing the roc_auc_score
print(f'For the Logistic Regression Model:\nROC_AUC_Score: {roc_auc_score(y_test, y_pred_probs):.2f}%')

For the Logistic Regression Model:
ROC_AUC_Score: 0.99%


It would appear that the Logistic Regression Model performed very well on this data set. 
It's performance actually exceeded my expectations. Despite being a simpler model when
compared to other classification models it still performed very well.\
However let's now see whether other models will perform as well or even better on the same data.

### Decision Tree Model

Let us now see whether a decision tree model can perform as well or even outperform the 
Logistic Regression model.

In [143]:
# Importing the Decision Tree Classifier from scikit-learn library
from sklearn.tree import DecisionTreeClassifier

In [146]:
# Creating a seed to use for random_state
SEED=101

In [148]:
# Instantiating DecisionTreeClassifer as dtree
dtree = DecisionTreeClassifier(max_depth=3, random_state=SEED)

In [181]:
# Creating a pipeline consisting of StandardScaler and DecisionTreeClassifier
pipeline_dtree = make_pipeline(scaler, dtree)

In [183]:
# Fitting the pipeline to the data
pipeline_dtree.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('decisiontreeclassifier',
                 DecisionTreeClassifier(max_depth=3, random_state=101))])

Now that we have trained our Decision Tree Model on the data we can now 
make predictions and evaluate the model's performance

In [194]:
# Making predictions on the test_data
y_pred = pipeline_dtree.predict(X_test)
# Predicting probabilities to be used in roc_auc_score
y_pred_probs = pipeline_dtree.predict_proba(X_test)[:,1]

In [196]:
# Printing the confusion matrix
print('For the Decision Tree Model:\n')
print(confusion_matrix(y_test, y_pred))
print('\n')
# Printing the classification report
print(classification_report(y_test, y_pred))

For the Decision Tree Model:

[[102   3]
 [  7  59]]


              precision    recall  f1-score   support

           B       0.94      0.97      0.95       105
           M       0.95      0.89      0.92        66

    accuracy                           0.94       171
   macro avg       0.94      0.93      0.94       171
weighted avg       0.94      0.94      0.94       171



In [200]:
# Printing the roc_auc_score
print(f'For the Decision Tree Model:\nROC_AUC_Score: {roc_auc_score(y_test, y_pred_probs):.2f}%')

For the Decision Tree Model:
ROC_AUC_Score: 0.93%


The Decision Tree Model's results are also good. However it falls slightly below that of the Logistic Regression model. Let's finally try a Random Forest Model and see what the performance will be this time around

### Random Forests Model

Random Forests is an ensemble of multiple decision trees and so it should rightfully outperform
a single decision tree. However will it outperform the Logistic Regression model which has become our benchmark? Well let's see as we train, predict and finally evaluate our model

In [205]:
# Importing RandomForestsClassifier from scikit-learn library
from sklearn.ensemble import RandomForestClassifier

In [210]:
# Instantiating RandomForestsClassifier as rfc
rfc = RandomForestClassifier(n_estimators=25, random_state=SEED)

In [212]:
# Making a pipeline consisting of StandardScaler and RandomClassifier
pipeline_rfc = make_pipeline(scaler, rfc)

In [216]:
# Fitting the pipeline to the training data
pipeline_rfc.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestclassifier',
                 RandomForestClassifier(n_estimators=25, random_state=101))])

In [224]:
# Predicting on the test data
y_pred = pipeline_rfc.predict(X_test)
# Predicting probabilites to be used in roc_auc_score
y_pred_probs = pipeline_rfc.predict_proba(X_test)[:,1]

In [226]:
# Printing the confusion matrix
print('For the Random Forests Model:\n')
print(confusion_matrix(y_test, y_pred))
print('\n')
# Printing the classification report
print(classification_report(y_test, y_pred))

For the Random Forests Model:

[[100   5]
 [  4  62]]


              precision    recall  f1-score   support

           B       0.96      0.95      0.96       105
           M       0.93      0.94      0.93        66

    accuracy                           0.95       171
   macro avg       0.94      0.95      0.94       171
weighted avg       0.95      0.95      0.95       171



In [227]:
# Printing the roc_auc_score
print(f'For the Random Forests Model:\nROC_AUC_Score: {roc_auc_score(y_test, y_pred_probs):.2f}%')

For the Random Forests Model:
ROC_AUC_Score: 0.98%


On average the Random Forests Model only did slighty better than the Decision Tree Model looking at the classification report and bit better on the roc auc score.\
However when comparing the confusion matrix and classification report of the Random Forests
Classifier with that of the Logistic Regression model it can be seen that it fell behind in both precision and recall.\
It is worth noting that since this is a breast cancer data set the target is diagnosing a 
tumor as either benign or malignant. This means that the metric of high importance in 
evaluating a model is **recall** as it is more important to reduce the rate of false negatives.\
In essence it would be much more costly to misdiagnose a malignant tumor as benign, than to 
misdiagnose a benign tumor as malignant.\
Therefore in this project a model's true value is in how high its **recall** metric is and currently the highest recall is the Logistic Regression model. Let's see whether another model can give us similar or even better results

### XGBoost

Extreme gradient boosting with the use of XGBoost is an effective machine learning
technique that makes use of powerful XGBoost models. Let's see whether this powerful model 
will be able to perform as well as the Logistic Regression model or even better.

In [239]:
# Importing the xgboost library
import xgboost as xgb

In [244]:
# Instanting XGBoostClassifier as xg_cl
xg_cl = xgb.XGBClassifier(objective='binary:logistic', seed=SEED, max_depth=3)

Unlike the previous machine learning models we built, XGBoost requires the target 
column be one hot encoded into 0s and 1s and not objects.\
In order to overcome this we will use LabelEncoder to convert the target column values
to the appropriate format to be used for training the XGBoostClassifier.

In [255]:
# Importing LabelEncoder from scikit-learn library
from sklearn.preprocessing import LabelEncoder

In [257]:
# Instantiating LabelEncoder as le
le = LabelEncoder()

In [272]:
# Fitting and transforming the training target values
y_train_le = le.fit_transform(y_train)

In [274]:
# Only transforming the test target values to avoid overfitting
y_test_le = le.transform(y_test)

In [275]:
# Creating a pipeline consisting of StandardScaler and XGBoostClassifier
pipeline_xgcl = make_pipeline(scaler, xg_cl)

In [276]:
# Fitting the pipeline object to the training data
pipeline_xgcl.fit(X_train, y_train_le)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('xgbclassifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=False, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [283]:
# Predicting on the test data
y_pred = pipeline_xgcl.predict(X_test)
# Predicting probabilities to use for roc_auc
y_pred_probs = pipeline_xgcl.predict_proba(X_test)[:,1]

In [285]:
# Printing the confusion matrix
print('For the XGBoost Model:\n')
print(confusion_matrix(y_test_le, y_pred))
print('\n')
# Printing the classification report
print(classification_report(y_test_le, y_pred))

For the XGBoost Model:

[[103   2]
 [  3  63]]


              precision    recall  f1-score   support

           0       0.97      0.98      0.98       105
           1       0.97      0.95      0.96        66

    accuracy                           0.97       171
   macro avg       0.97      0.97      0.97       171
weighted avg       0.97      0.97      0.97       171



In [287]:
# Printing the roc_auc_score
print(f'For the XGBoost Model:\nROC_AUC_Score: {roc_auc_score(y_test_le, y_pred_probs):.2f}%')

For the XGBoost Model:
ROC_AUC_Score: 0.98%


From the results it can be seen that the XGBoost model came the closest to the Logistic 
Regression model in terms of **recall** which is of importance.\
It is worth noting that the XGBoostClassifier here has not been tuned and so it is possible
that with proper hyperparamter tuning it may outperform the Logistic Regression model.\
Either ways it did quite well on the predictions so that is fine for now. Also this is a small
data set. Had it been a much larger data set the XGBClassifier may well outperform the Logistic 
Regression model

### Final thoughts

In my opinion this was a good project with an interesting turn of events. It underscores the
fact that at times a simpler model may be a better fit for a data set than a more 
powerful model.\
And so to conclude, the model with the best performance is the **Logistic Regression Model**.